/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.io.IOException;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;

/**
 *
 * @author karthi
 */
public class movie extends javax.swing.JFrame {

    /**
     * Creates new form movie
     */
    public movie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sel = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vi = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("TOP IMDB MOVIES - WORLD CINEMA");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        sel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        sel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All_movies", "HollyWood_movies", "French_movies", "Iran_movies", "Indian_movies", "Korean_movies" }));
        sel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Proceed");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        vi.setBackground(new java.awt.Color(102, 255, 204));
        vi.setColumns(20);
        vi.setFont(new java.awt.Font("Lucida Sans Unicode", 0, 18)); // NOI18N
        vi.setForeground(new java.awt.Color(0, 0, 204));
        vi.setRows(5);
        vi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(vi);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("Clear");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //all movies
        if("All_movies".equals(sel.getSelectedItem()))
        {   vi.setText(" ");
            try{
Document doc=Jsoup.connect("https://www.imdb.com/list/ls002448041/").userAgent("Mozilla/63.0.3").get();
Elements temp=doc.select("div.lister-item-content");

int i=0;
for(Element movieList:temp)
{
	i++;
        
        //movieList.getElementsByTag("a").first().text();
	//vi.setText(String.valueOf(i));
        vi.append(i+"  "+movieList.getElementsByTag("a").first().text()+"\n");
        
        
        
        
        
        
    
                     
}
}
        
        
catch (IOException e) {
e.printStackTrace();
}
        }
        // indian moives
        
        else if("Indian_movies".equals(sel.getSelectedItem()))
        {   vi.setText(" ");
            try{
Document doc=Jsoup.connect("https://www.imdb.com/list/ls053327568/?sort=user_rating,desc&st_dt=&mode=detail&page=1").userAgent("Mozilla/63.0.3").get();
Elements temp=doc.select("div.lister-item-content");

int i=0;
for(Element movieList:temp)
{
	i++;
        
        //movieList.getElementsByTag("a").first().text();
	//vi.setText(String.valueOf(i));
        vi.append(i+"  "+movieList.getElementsByTag("a").first().text()+"\n");
    
                     
}
}
        
        
catch (IOException e) {
e.printStackTrace();
}
        }
        
        //korean movies
        
        else if("Korean_movies".equals(sel.getSelectedItem()))
        {   vi.setText(" ");
            try{
Document doc=Jsoup.connect("https://www.imdb.com/list/ls000557689/").userAgent("Mozilla/63.0.3").get();
Elements temp=doc.select("div.lister-item-content");

int i=0;
for(Element movieList:temp)
{
    
	i++;
        
        //movieList.getElementsByTag("a").first().text();
	//vi.setText(String.valueOf(i));
        vi.append(i+"  "+movieList.getElementsByTag("a").first().text()+"\n");
    
                     
}
}
        
        
catch (IOException e) {
e.printStackTrace();
}
        }
        
        
        
        else if("HollyWood_movies".equals(sel.getSelectedItem()))
        {   vi.setText(" ");
            try{
Document doc=Jsoup.connect("https://www.imdb.com/list/ls009454990/").userAgent("Mozilla/63.0.3").get();
Elements temp=doc.select("div.lister-item-content");

int i=0;
for(Element movieList:temp)
{
    
	i++;
        
        //movieList.getElementsByTag("a").first().text();
	//vi.setText(String.valueOf(i));
        vi.append(i+"  "+movieList.getElementsByTag("a").first().text()+"\n");
    
                     
}
}
        
        
catch (IOException e) {
e.printStackTrace();
}
        }
        
        
        
        else if("French_movies".equals(sel.getSelectedItem()))
        {   vi.setText(" ");
            try{
Document doc=Jsoup.connect("https://www.imdb.com/list/ls000452439/").userAgent("Mozilla/63.0.3").get();
Elements temp=doc.select("div.lister-item-content");

int i=0;
for(Element movieList:temp)
{
    
	i++;
        
        //movieList.getElementsByTag("a").first().text();
	//vi.setText(String.valueOf(i));
        vi.append(i+"  "+movieList.getElementsByTag("a").first().text()+"\n");
    
                     
}
}
        
        
catch (IOException e) {
e.printStackTrace();
}
        }
        
        else if("Iran_movies".equals(sel.getSelectedItem()))
        {   vi.setText(" ");
            try{
Document doc=Jsoup.connect("https://www.imdb.com/list/ls070009636/").userAgent("Mozilla/63.0.3").get();
Elements temp=doc.select("div.lister-item-content");

int i=0;
for(Element movieList:temp)
{
    
	i++;
        
        //movieList.getElementsByTag("a").first().text();
	//vi.setText(String.valueOf(i));
        vi.append(i+"  "+movieList.getElementsByTag("a").first().text()+"\n");
    
                     
}
}
        
        
catch (IOException e) {
e.printStackTrace();
}
        }
        
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
vi.setText(" ");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(movie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new movie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> sel;
    private javax.swing.JTextArea vi;
    // End of variables declaration//GEN-END:variables
}
